name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Contract tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup environment
        run: |
          pip install eth-brownie
          npm install -g ganache-cli

      - name: Generate contracts
        run: ./processing.py

      - name: Run tests
        run: brownie test
